### ISSUE TITLE
GUI conflict with StoneQuarry?

### ISSUE THREAD

**Issue by robert-bowman** [p3t3rix-vsmods/VsProspectorInfo#19]
Hi, Great Mod.  I have been using it for several weeks.  

I added 'stonequarry' and the game crashed.  I had not run the stonequarry object mapping yet, so I removed prospectorinfo and reran the game; the object mapping completed.  I then readded prospectorinfo and the game crashed again.  GUI conflict?

Thanks for your consideration :)

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.8 (Stable)
10/15/2022 6:02:11 PM: Critical error occurred in the following mod: prospectorinfo@4.1.2
Loaded Mods: animalcages@2.0.6, buildersblocks@1.0.0, meteoricexpansion@1.2.2, MoreTorchHolders@1.0.0, primitivesurvival@3.0.5, stacks@1.0.4, vtpp@1.0.0, game@1.17.8, zoombuttonreborn@1.3.0, carrycapacity@0.6.5, fromgoldencombs@1.3.15, hudclock@2.8.0, medievalexpansion@3.8.1, petai@1.5.4, prospectorinfo@4.1.2, stonequarry@2.0.0-rc.4, vanvar@2.0.1, creative@1.17.8, survival@1.17.8, woodchests@1.0.3, metalrecovery@0.1.18-rc.2, cobvoices@1.0.0, onestick@1.0.1, wolftaming@1.5.3
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 238
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 395
   at ProspectorInfo.Map.GuiProspectorInfoSetting.SetupDialog()
   at ProspectorInfo.Map.GuiProspectorInfoSetting..ctor(ICoreClientAPI capi, ModConfig config, Action`1 rebuildMap)
   at ProspectorInfo.Map.ProspectorOverlayLayer..ctor(ICoreAPI api, IWorldMapManager mapSink)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.GameContent.WorldMapManager.OnLoaded() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 218
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientMain.OnAllAssetsLoaded_ClientSystems(Int32 i) in VintagestoryLib\Client\ClientMain.cs:line 947
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1168
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 238
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 395
   at ProspectorInfo.Map.GuiProspectorInfoSetting.SetupDialog()
   at ProspectorInfo.Map.GuiProspectorInfoSetting..ctor(ICoreClientAPI capi, ModConfig config, Action`1 rebuildMap)
   at ProspectorInfo.Map.ProspectorOverlayLayer..ctor(ICoreAPI api, IWorldMapManager mapSink)
```

**Comment by robert-bowman** [comment]
Quick update.  I disabled the stonequarry mod and found that it still crashed, so I deleted the pi config file.  Still crashed.  Removed the stonequarry mod.  Crashed.  deleted the pi config and it started.

Then added the stonequarry mod again and it started...  So it seems to be something in the original start after installing the stonequarry mod.  I did not save the pi config file, so I don't have that to compare to the one that seems to have been corrupted.

I loaded another game that I had not run with stonequarry and the object mapping went fine.  No crash.

**Comment by robert-bowman** [comment]
Were you able to replicate?

**Comment by GGGuenni** [comment]
Sorry wasn't able to look at it yet
I will try to look at it this week

**Comment by robert-bowman** [comment]
S'all good.  Just wanted to let you know what I found.  Thanks.

**Comment by GGGuenni** [comment]
Sadly I haven't been able to replicate the issue by installing ProspectiorInfo 4.1.2 and stonequarry 2.0.0-rc.4 completely fresh.
If I understand correctly you managed to "fix" the problem yourself for now? Then I wouldn't prioritize this until there is a consistent way to replicate the issue.

**Comment by robert-bowman** [comment]
Thanks for your help.  Yes, removing the config file and letting the mod recreate it seems to have resolved the problem.

**Comment by robert-bowman** [comment]
Once again.  Thanks.  :)
