### ISSUE TITLE
Command `.pi` breaks in 1.18-pre5

### ISSUE THREAD

**Issue by hlangeveld** [p3t3rix-vsmods/VsProspectorInfo#25]
Basic function works out of the box on VS 1.18-pre.

After I prospected my third chunk the overlay disappeared.
Attempting to restore it with the `.pi` command crashes the game.

I had no expectations, so no harm done.

```
Game Version: v1.18.0-pre.5 (Unstable)
09/03/2023 22:08:25: Critical error occurred
Loaded Mods: game@1.18.0-pre.5, prospectorinfo@4.1.2, creative@1.18.0-pre.5, survival@1.18.0-pre.5
System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Vintagestory.API.Common.CmdArgs.PopBool(System.Nullable`1<Boolean>)'.
   at ProspectorInfo.Map.ProspectorOverlayLayer.OnPiCommand(Int32 groupId, CmdArgs args)
   at Vintagestory.Common.ChatCommandApi.<>c__DisplayClass24_0.<RegisterCommand>b__0(TextCommandCallingArgs args) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 246
   at Vintagestory.Common.ChatCommandImpl.callHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 282
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientCommand(String message, Int32 groupid) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 783
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 735
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 337
   at Vintagestory.Client.NoObf.HudDialogChat.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 550
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1711
```

**Comment by Wooza** [comment]
Thanks for reporting. #23 will hopefully address this, once 1.18 is released.

**Comment by Wooza** [comment]
I uploaded a work in progress version that should work with 1.18.0-pre7 in #23. Feel free to try it.

**Comment by hlangeveld** [comment]
That appears to work. Tested for 5 minutes in single player.

**Comment by p3t3rix** [comment]
Should work with version 4.2.0 and game version 1.8.0 upwards, if not please open another ticket
